server.servlet.context-path: /authsample

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  datasource.platform: h2

application:
  default-role: user
  header.authorization.bearer: Bearer
  jwt:
    secret-key: secret-key
    expiration: 60000
logging.level:
  org.zalando.logbook: trace
  ru.kononov.authsample: debug
